//3.1: all persons route
GET http://localhost:3001/api/persons/

### 
//3.2: info route
GET http://localhost:3001/info/

###
//3.3: get exisintng person by id route (expec2ting Arto Hellas)
GET http://localhost:3001/api/persons/1

###
//3.3: get nonexisting person by id route 
GET http://localhost:3001/api/persons/0
